apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction-service
  ports:
    - protocol: TCP
      port: 80  # The port the service is exposed on
      targetPort: 8082  # The container port to send traffic to
  type: LoadBalancer
